#!/bin/bash

list=(
  'include/validation/validation.hpp'
  'include/validation/events_from_slice.hpp'
  'include/validation/types.hpp'
  'src/validation.cpp'
)

for item in "${list[@]}"; do
  echo "cp ./$item ../json-schema-validation/$item"
  cp "./$item" "../json-schema-validation/$item"
done
